### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by licensed** [deadsy/sdfx#15]
Congratulations on this project!
It's my first time with golang and i got error while build
Steps to reproduce:
git clone git@github.com:deadsy/sdfx.git
cd sdfx/examples/nutsandbolts/
go build main.go

 ✘ licensed@licensed  ~/gitz/sdfx/examples/nutsandbolts   master  go build main.go 
main.go:11:8: cannot find package "github.com/deadsy/sdfx/sdf" in any of:
        /usr/lib/go/src/github.com/deadsy/sdfx/sdf (from $GOROOT)
        /home/licensed/go/src/github.com/deadsy/sdfx/sdf (from $GOPATH)

Line 11 is:  import . "github.com/deadsy/sdfx/sdf"

**Comment by deadsy** [comment]
I'd say the code is not in the place indicated in the GOPATH variable.
ie - you cloned into gitz/sdfx
your GOPATH is something like: /home/licensed/go

You need to clone into:
$GOPATH/src/github.com/deadsy/sdfx

Also: "go build" in the specific example directory will get the job done.
