### ISSUE TITLE
Guidance in creating a manifold

### ISSUE THREAD

**Issue by delaneyj** [deadsy/sdfx#3]
Know how to 3d model and program in Go so this seems way better than dealing with openscad.  [Want to create a 6 in to dual 4 in manifold for my dust collector.
![manifold](https://user-images.githubusercontent.com/438252/34311999-cba8ae92-e715-11e7-8eac-ff523c3b57a1.png)

There  are many parametric details to this and seemed like the perfect project to use sdfx for but don't know where to get started.

**Comment by deadsy** [comment]
Lot's of interesting curves on that render - suggesting some sort of NURBS or 3d bezier curves.

Making a functional 3-way manifold in  sdfx should be easy enough. Essentially it's three intersecting cylinders. I'd create an outer shell and an inner core and the subtract them - that way the inside will be clean. Some blending at the intersections will smooth out the transitions at the joins. 
Take a look at examples/challenge/cc18.go - the cc18b example is similar to what you want.
