### ISSUE TITLE
Pack models together tightly

### ISSUE THREAD

**Issue by Megidd** [deadsy/sdfx#62]
It's intended to find some ways of arranging 3D models to minimize wasted space. In other words, it's desired to reduce the total volume of `N` 3D models packed together. The figures below show 2 and 4 models packed together.

Converting the 3D models to SDF might help with developing such an algorithm. I'm exploring the feasibility of using SDF for such an algorithm. Looks like SDF might provide a lot of conveniences.

My question is whether SDF is a good fit for such a problem domain. Is anyone aware of an SDF tool that does the above process? Are there any SDF tools that I might want to look at them to develop such an algorithm?

![Screen Shot 2023-01-10 at 14 08 22](https://user-images.githubusercontent.com/17475482/211530331-9bfb35d3-6e65-459d-b84d-dd2fb2dfa358.png)

**Comment by deadsy** [comment]
I assume you know about:

https://github.com/fogleman/pack3d

**Comment by Megidd** [comment]
@deadsy Yes :) So, I guess there is no other helpful tool to look at.

**Comment by Megidd** [comment]
Investigations indicate that an external package might be a good starting point for my use cases: https://github.com/Megidd/pack3d/pull/1
