### ISSUE TITLE
Creating an arbitraty shape for a chain

### ISSUE THREAD

**Issue by Megidd** [deadsy/sdfx#75]
Shapes like gyroid can already be created by signed distance functions, SDF: 

https://github.com/deadsy/sdfx/blob/7a4c3139ef6ca8511e44080aaf971b9606460c84/sdf/gyroid.go#L23

I wonder if any arbitrary shape is feasible to be created by SDF. Shapes like [this type of chain](https://crafts.stackexchange.com/q/11919/10045). I just want to make sure there is no possible hurdle.

**Comment by deadsy** [comment]
SDFs are general so you can create arbitrary objects. It's conceivable that there is a mathematical oddity implementing the SDF for a chain, but in practice you typically construct such things with CSG on primitive shapes. E.g. everything in the objects directory- useful things, all built from simpler primitives.
