### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Megidd** [deadsy/sdfx#77]
Having updated to the latest version by `go get -u all` and then building, an error is thrown:

> `..\..\pkg\mod\github.com\deadsy\sdfx@v0.0.0-20231227000239-7bfc0b2603e7\sdf\triangle3.go:73:9: cannot use r (variable of type rtreego.Rect) as *rtreego.Rect value in return statement`

![2024-01-06 04_11_06-Developer Command Prompt for VS 2022](https://github.com/deadsy/sdfx/assets/17475482/42249e36-bab8-404c-81cf-dfbf84e9cb60)

The error is related to this statement:

```go
// Bounds returns a r-tree bounding rectangle for the triangle.
func (t *Triangle3) Bounds() *rtreego.Rect {
	b := t.BoundingBox()
	r, _ := rtreego.NewRectFromPoints(v3ToPoint(b.Min), v3ToPoint(b.Max))
	return r // ** error here
}
```

![2024-01-06 04_15_47-triangle3 go - sdfx - Visual Studio Code](https://github.com/deadsy/sdfx/assets/17475482/aaa8b962-073e-4eb5-9edc-247e0935f800)

**Comment by Megidd** [comment]
You know what, this error shouldn't be thrown, since the variable types are all consistent:

![2024-01-06 04_25_55-triangle3 go - sdfx - Visual Studio Code](https://github.com/deadsy/sdfx/assets/17475482/d62bd88a-f1f5-47b2-844c-49eb44ded7b0)

I'm not sure what I'm missing 🙄

**Comment by Megidd** [comment]
Well, the error got resolved by removing `go.mod` of the dependent repository and then running:

```go
go mod init
go mod tidy
go build
```

Anyways, it's resolved now ✔️ I'm not sure what was the cause 🙄

**Comment by deadsy** [comment]
The rtree package author changed the api. I updated sdfx to match the new api.
